### ISSUE TITLE
Changing certain settings results in excessive disk usage

### ISSUE THREAD

**Issue by peterkrull** [pop-os/cosmic-settings#474]
Whenever changing some settings, the application freezes momentarily, and causes high disk usage. It mostly seems to happen for the appearance, panel and dock settings. The impact of this is much worse on a slower drive.

https://github.com/user-attachments/assets/0df7c7e0-3a01-4e13-a424-e48598ae9efb

It is probably also why Brodie had a bad experience changing settings: https://youtu.be/BG9JSLk4GfE?t=3309

**Comment by mmstick** [comment]
Panel settings fix applied here: 66f32168cabc30ec990befeb3e6bb788e786cd9c

**Comment by peterkrull** [comment]
Just tried it out, and it definitely feels better to use the slider, though I am able to make the panel crash by moving the slider handle back and forth for a few  seconds, about 8s in my case, or by switching a toggle repeatedly.

```
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("name", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("anchor", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("anchor_gap", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("layer", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("keyboard_interactivity", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("size", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("output", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("background", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("plugins_wings", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("plugins_center", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("expand_to_edges", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("padding", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("spacing", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("border_radius", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("exclusive_zone", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("autohide", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("margin", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Failed to get entry value: GetKey("opacity", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:28:15 fedora cosmic-panel[33727]: Erroneous EGL call didn't set EGLError
Aug 12 22:28:15 fedora cosmic-panel[33727]: thread 'main' panicked at 'Failed to create EGL Surface: Unknown(0)': cosmic-panel-bin/src/space/panel_space.rs:977
                                               0: <unknown>
                                               1: <unknown>
                                               2: <unknown>
                                               3: <unknown>
                                               4: <unknown>
                                               5: <unknown>
                                               6: <unknown>
                                               7: <unknown>
                                               8: <unknown>
                                               9: <unknown>
                                              10: <unknown>
                                              11: <unknown>
                                              12: <unknown>
                                              13: <unknown>
                                              14: <unknown>
                                              15: <unknown>
                                              16: <unknown>
                                              17: <unknown>
                                              18: <unknown>
                                              19: <unknown>
                                              20: <unknown>
```

and 

```
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("name", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("anchor", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("anchor_gap", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("layer", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("keyboard_interactivity", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("size", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("output", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("background", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("plugins_wings", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("plugins_center", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("expand_to_edges", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("padding", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("spacing", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("border_radius", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("exclusive_zone", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("autohide", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("margin", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: Failed to get entry value: GetKey("opacity", Os { code: 24, kind: Uncategorized, message: "Too many open files" })
Aug 12 22:38:27 fedora cosmic-panel[40429]: thread 'main' panicked at 'Out of file descriptors: IoError(Os { code: 24, kind: Uncategorized, message: "Too many open files" })': cosmic-panel-bin/src/iced/mod.rs:267
                                               0: <unknown>
                                               1: <unknown>
                                               2: <unknown>
                                               3: <unknown>
                                               4: <unknown>
                                               5: <unknown>
                                               6: <unknown>
                                               7: <unknown>
                                               8: <unknown>
                                               9: <unknown>
                                              10: <unknown>
                                              11: <unknown>
                                              12: <unknown>
                                              13: <unknown>
                                              14: <unknown>
                                              15: <unknown>
                                              16: <unknown>
                                              17: <unknown>
```

Both settings and panel are just compiled from source

**Comment by BrodieRobertson** [comment]
The problem is considerably better now, sliders now function on a HDD but settings like active window hint size still take upwards of 6 seconds to apply per press of the button

**Comment by git-f0x** [comment]
Not sure if it's possible, but it would be nice if the changes were immediately reflected in the UI as now, but weren't written to disk until a timeout (e.g. 10s) or the Settings app is closed. But since the components look at the config files for changes, not sure if it's possible to have a temporary change that isn't written to disk.
An apply button would probably be easier, though potentially annoying.

**Comment by BrodieRobertson** [comment]
It may not be intended but it's absolutely possible, as shown by #476 a bug where the setting that's in the config file and the setting shown in the GUI can get desynced from each other

**Comment by wash2** [comment]
> The problem is considerably better now, sliders now function on a HDD but settings like active window hint size still take upwards of 6 seconds to apply per press of the button

Some similar updates can be made to the appearance page to fix that as well. Changing some options on the appearance page will regenerate the theme, but not all settings will be different, so it should probably use some of the more granular config methods for updating the values.

> Just tried it out, and it definitely feels better to use the slider, though I am able to make the panel crash by moving the slider handle back and forth for a few seconds, about 8s in my case, or by switching a toggle repeatedly.

I've not been able to recreate this with my panel settings, but could you create an issue for this in https://github.com/pop-os/cosmic-panel with a screenshot of your panel settings?

**Comment by l-const** [comment]
Yeah, this is annoying and it is the only thing that is "laggy" in my desktop. For example, we do not need to write everything when the active window hint size is changed, need to change how the ThemeBuilder is used to set the configs and the _needs_update_ flag and do the config changes "atomic" like this PR did for cosmic-term here: https://github.com/pop-os/cosmic-term/commit/c4cb09f18394913d8e76d1a336d10241b9b1da65 using `config_set!()`
